name: Billa
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #local store 
  shared_preferences: ^2.2.2
  get: ^4.6.6
  pinput: ^3.0.1
  intl: ^0.17.0
  image_picker: ^1.0.5
  dio: ^5.4.0
  dropdownfield2: ^1.0.7
  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  quickalert: ^1.0.2
  carousel_slider: ^4.2.1
  device_info: ^2.0.3
  uuid: ^4.2.2
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  intl_phone_field: ^3.2.0
  flutter_widget_from_html: ^0.14.9
  flutter_local_notifications: ^16.2.0
  razorpay_flutter: ^1.3.0
  vibration:
  html: ^0.15.4
  webview_flutter: ^4.5.0
  upi_india: ^3.0.1
  marquee_list: ^1.0.0
  
flutter/services.dart:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For Detailss regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

  fonts:
    - family: Roboto1
      fonts:
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: fonts/RobotoCondensed-Light.ttf
        - asset: fonts/RobotoCondensed-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For Detailss regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
