// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Irdytd530CHyJ0h5P5N_ohvOtIMvLq8',
    appId: '1:930760873616:web:9a12908401b5a968faea15',
    messagingSenderId: '930760873616',
    projectId: 'winner-9b9d4',
    authDomain: 'winner-9b9d4.firebaseapp.com',
    storageBucket: 'winner-9b9d4.appspot.com',
    measurementId: 'G-ZE734PEXEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm98GijFlaTA9AefZCWCE-sSerc20obbU',
    appId: '1:930760873616:android:84ab40c8e82eb93dfaea15',
    messagingSenderId: '930760873616',
    projectId: 'winner-9b9d4',
    storageBucket: 'winner-9b9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Itd1lfmzELLU4KvTrnmoa6v9qq8FVpo',
    appId: '1:930760873616:ios:dcfc5ef46ff8f3e9faea15',
    messagingSenderId: '930760873616',
    projectId: 'winner-9b9d4',
    storageBucket: 'winner-9b9d4.appspot.com',
    iosBundleId: 'com.example.Billa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Itd1lfmzELLU4KvTrnmoa6v9qq8FVpo',
    appId: '1:930760873616:ios:7df31a0a867b3e01faea15',
    messagingSenderId: '930760873616',
    projectId: 'winner-9b9d4',
    storageBucket: 'winner-9b9d4.appspot.com',
    iosBundleId: 'com.example.Billa.RunnerTests',
  );
}
